# Generated by Django 5.1.2 on 2024-10-21 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('biographie', models.TextField()),
                ('date_naissance', models.DateField()),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_auteurs/')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.TextField()),
                ('site_web', models.URLField()),
                ('email_contact', models.EmailField(max_length=254)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_editeurs/')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etat', models.CharField(choices=[('Neuf', 'Neuf'), ('Bon', 'Bon'), ('Acceptable', 'Acceptable')], max_length=50)),
                ('date_acquisition', models.DateField()),
                ('emplacement', models.CharField(max_length=255)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_emprunt', models.DateTimeField()),
                ('date_retour_prevue', models.DateTimeField()),
                ('date_retour_reelle', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('En retard', 'En retard')], max_length=50)),
                ('remarques', models.TextField(blank=True, null=True)),
                ('exemplaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emprunts', to='quickstart.exemplaire')),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('resume', models.TextField()),
                ('date_publication', models.DateField()),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('nombre_de_pages', models.PositiveIntegerField()),
                ('langue', models.CharField(max_length=50)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='couvertures_livres/')),
                ('editeur', models.CharField(max_length=255)),
                ('format', models.CharField(choices=[('Broché', 'Broché'), ('Relié', 'Relié'), ('Numérique', 'Numérique')], max_length=50)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='quickstart.auteur')),
            ],
        ),
        migrations.AddField(
            model_name='exemplaire',
            name='livre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplaires', to='quickstart.livre'),
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('commentaire', models.TextField()),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('recommande', models.BooleanField(default=False)),
                ('titre', models.CharField(max_length=100)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='quickstart.livre')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('note', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('visible', models.BooleanField(default=True)),
                ('modere', models.BooleanField(default=False)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='quickstart.livre')),
            ],
        ),
    ]
