# Generated by Django 5.1.2 on 2024-10-21 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livre',
            name='editeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='quickstart.editeur'),
        ),
    ]
